apiVersion: json.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: check-public-access-cidr
  annotations:
    policies.kyverno.io/title: Check Public Access CIDR
    policies.kyverno.io/category: EKS Best Practices
    policies.kyverno.io/severity: high
    policies.kyverno.io/description: >-
      Restricting public access CIDRs to specific IP ranges enhances security by limiting access to the EKS cluster endpoint.
spec:
  rules:
    - name: check-public-access-cidr
      match:
        any:
        - (planned_values.root_module.child_modules | length(@) > `0`): true
      assert:
        all:
        - message: Public access CIDRs must not be set to 0.0.0.0/0
          check:
            ~.(planned_values.root_module.child_modules[0].resources[?type=='aws_eks_cluster'].values):
              (vpc_config[0].public_access_cidrs[?@ == '0.0.0.0/0'] | length(@)): 0 