apiVersion: json.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: check-public-endpoint
  annotations:
    policies.kyverno.io/title: Check Public Endpoint
    policies.kyverno.io/category: EKS Best Practices
    policies.kyverno.io/severity: high
    policies.kyverno.io/description: >-
      Disabling the public endpoint minimizes the risk of unauthorized access and potential security breaches by reducing the attack surface of the EKS control plane.
spec:
  rules:
    - name: check-public-endpoint
      match:
        any:
        - (planned_values.root_module.child_modules | length(@) > `0`): true
      assert:
        all:
        - message: Public access to EKS cluster endpoint must be explicitly set to false
          check:
            (planned_values.root_module.child_modules[0].resources[?type=='aws_eks_cluster'].values.vpc_config[0].endpoint_public_access | [0]): false

