apiVersion: json.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: check-secrets-encryption
  annotations:
    policies.kyverno.io/title: Check Secrets Encryption
    policies.kyverno.io/category: EKS Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/description: >-
      Secrets encryption is essential to encrypt sensitive data, such as secrets and credentials stored within Kubernetes, adding an additional layer of protection against unauthorized access
spec:
  rules:
    - name: check-secrets-encryption
      match:
        any:
        - (planned_values.root_module.child_modules[*].resources[?type=='aws_eks_cluster'] | length(@) > `0`): true
      assert:
        any:
        - message: Secrets encryption must be properly configured
          check:
            ~.(planned_values.root_module.child_modules[*].resources[?type=='aws_eks_cluster'].values):
              (encryption_config[0].resources[0] == 'secrets'): true