name: Kyverno Scan K8s Demo
run-name: ${{ github.actor }} has triggered Scan Action 🚀
on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  NCTL-Scan-K8s:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Kyverno CLI
        uses: kyverno/action-install-cli@v0.2.0

      - run: echo "🖥️ The workflow is now ready to test your code on the runner."

      - name: Check install
        run: kyverno version

      - name: Kyverno Scan - Kubernetes
        run: kyverno apply controls/pod-security --resources config-files/k8s

      - name: NCTL Scan - Kubernetes Detailed Report
        run: nctl scan kubernetes --policies controls/pod-security --resources config-files/k8s -p

      - run: echo "🍏 This job's status is ${{ job.status }}."
